version: '3'

networks:
  web-network:

services:
  docker-nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  docker-php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./app:/var/www
    networks:
      - web-network

  docker-php-cli:
    working_dir: "/var/www"
    build:
      context: ./php-cli
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www
    networks:
      - web-network

  db:
    image: mariadb:10.2.26
    environment:
      MYSQL_DATABASE: symsoc
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    networks:
      - web-network
